version: '3.7'
services:
  db:
    image: 'postgres:12'
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes:
      - dbvolume:/data
    environment: {
      POSTGRES_USER: "blog-user",
      POSTGRES_PASS: "password",
      POSTGRES_DB: "blog-prod"
    }

volumes:
  dbvolume: {}